name := "Simple Project"
version := "1.0"
scalaVersion := "2.12.7"
libraryDependencies += "org.apache.spark" %% "spark-core" % "2.4.4"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "2.4.4"
