all: help
##-------------------------------------------------------------------------
##
##	                                                                                                //
##	                                                                                             ///////
##	                                                                                            /////////
##	                                                                                           .//// //////            ,///
##	                                                                                           /////  //////  */////////////
##	                                                                                           ////     ///////////////////
##	                                                                                         //////      ////.     //////
##	                                                                                 //////////////              //////
##	                                                                            ,///////////*                  //////
##	                              ,,     ,,,      ,      ,,,    ,   ,    ,,,    //////////                   */////
##	             ,,,,,           ,.,     ,,,,   ,,,,   ,,      ,,,,,.   ,,,,      //////////////               //////
##	        ,,,,,,,,,,,,,,      ,  ,,   ,.     ,.  ,   .,,,    ,   ,    ,,,            /////  ,,,               //////
##	      ,,,,,,,,,,,,,,,,.                                                                ,,,,,,      ,, ///    */////
##	      ,,,,,      .,                                                                    ,,,,,     ,,,,  /////////////
##	      ,,,,,,,               ,,,,,,,,,,,,,,           ,,,,,,,,,,,,,,         ,,,,,,,,  ,,,,,,   ,,,,,,   ////////////
##	      .,,,,,,,,          ,,,,,,,,,,,,,,,,,,,      ,,,,,,,,,,,,,,,,,,,     ,,,,,,,,,,  ,,,,,, ,,,,,.
##	        .,,,,,,,,      ,,,,,,          ,,,,,,    ,,,,,,         ,,,,,,   ,,,,,,       ,,,,,,,,,,
##	           ,,,,,,,,   ,,,,,.            ,,,,,  .,,,,,            ,,,,,,  ,,,,,       .,,,,,,,,,,.
##	             ,,,,,,,  ,,,,,             ,,,,,  ,,,,,             ,,,,,.  ,,,,,       ,,,,,, ,,,,,,
##	    .,        ,,,,,, ,,,,,,            ,,,,,.  ,,,,,,            ,,,,,  ,,,,,,       ,,,,,    ,,,,,,
##	,,,,,,,,    .,,,,,,  ,,,,,,,,.      ,,,,,,,     ,,,,,,,      ,,  ,,,,,  ,,,,,       ,,,,,,     ,,,,,,,
##	 .,,,,,,,,,,,,,,,    ,,,,,,,,,,,,,,,,,,,,        ,,,,,,,,,,,,,, .,,,,,  ,,,,,       ,,,,,,       ,,,,,,,
##	    ,,,,,,,,,,      ,,,,,  ,,,,,,,,,,               .,,,,,,,,,. ,,,,,  ,,,,,,       ,,,,,.         ,,,,,,  . ,,
##	                    ,,,,,
##	                    ,,,,,
##
## ------------------------------------------------------------------------
## Available commands are:
## ------------------------------------------------------------------------
##
##	up:		Brings the environment on

.PHONY : up
up:
	docker-compose -f docker-compose.yml up -d

##	down:		Turns down the environment
.PHONY : down
down:
	docker-compose down

##	help:		Help of the project
.PHONY : help
help : Makefile
	@sed -n 's/^##//p' $<

##	datagen:	[SIZE_IN_BYTES]
##  			Generates a CSV of [SIZE_IN_BYTES] worth of data.
.PHONY: datagen
datagen :
	sh scripts/data-generator/data-generator.sh $(filter-out $@,$(MAKECMDGOALS))

##	datawipe:	Erases data generated by [generate-data] command
.PHONY: datawipe
datawipe :
	sh scripts/data-reset.sh

##	spkshell:	Opens the spark shell in spark-master
.PHONY: spkshell
spkshell :
	docker-compose exec spark-master /spark/bin/spark-shell

##	etlexec:	Executes the ETL on src/ folder
.PHONY: etlexec
etlexec:
	docker-compose exec spark-master /spark/bin/spark-shell -i /opt/spark-apps/main/scala/com/etlExample/Executor.scala

